kind: Deployment
apiVersion: apps/v1
metadata:
  name: inventory-app
  labels:
    app: inventory-app
    app.kubernetes.io/part-of: inventory
    app.openshift.io/runtime: quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-app
  template:
    metadata:
      labels:
        app: inventory-app
        deployment: inventory-app
    spec:
      containers:
        - name: inventory-app
          image: quay.io/rh_ee_ozimakov/inventory-app:latest
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: inventory-app
  labels:
    app: inventory-app
    app.kubernetes.io/part-of: inventory
spec:
  type: ClusterIP
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: inventory-app
    deployment: inventory-app
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: inventory-app
  labels:
    app: inventory-app
    app.kubernetes.io/part-of: inventory
spec:
  to:
    kind: Service
    name: inventory-app
    weight: 100
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None

