name: Release

on:
  release:
    types: [ created ]
  
jobs:
  build-inventory-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Print release version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Quarkus image
        run: |
          cd ./inventory-app
          ./mvnw -B package -Pnative -Dquarkus.native.container-build=true
          docker build -f src/main/docker/Dockerfile.native-micro -t quay.io/rh_ee_ozimakov/inventory-app:$VERSION .
          docker tag quay.io/rh_ee_ozimakov/inventory-app:$VERSION quay.io/rh_ee_ozimakov/inventory-app:latest
          docker push quay.io/rh_ee_ozimakov/inventory-app:$VERSION
          docker push quay.io/rh_ee_ozimakov/inventory-app:latest
